using System.Collections.Immutable;
using ImmutableGameObjects;

namespace DoomCore.Tests;

/// <summary>
/// The preview must always agree with what actually happens. It is generated by running the real
/// transform, so the decisive test is that preview-then-resolve equals resolve.
/// </summary>
public class DoomPreviewTests
{
	private static (GameState State, ImmutableList<GameEvent> Events) Do(
		GameState state,
		GameAction action
	) => state.AddAction(action).ProcessAllActions();

	private static RunCard Unit(string name, int power, int toughness, int cost = 0) =>
		new()
		{
			Name = name,
			Cost = cost,
			IsUnit = true,
			Power = power,
			Toughness = toughness,
		};

	private static Enemy Idler() =>
		new()
		{
			Name = "Idler",
			Health = 50,
			MaxHealth = 50,
			Intent = IntentKind.Wait,
		};

	[Test]
	public void ThePreviewMatchesWhatTheDoomActuallyDoes()
	{
		var run = new Run().WithCards([Unit("Committed", 2, 2), Unit("Hoarded", 1, 1)]);
		var committedId = run.Deck[0].RunCardId;

		(var state, _) = run.StartBattle(DoomScenario.Flood, countdown: 2, [Idler()]);

		var toPlay = state.CardsIn(ZoneType.Hand).First(c => c.RunCardId == committedId);
		(state, _) = Do(state, new PlayCardAction { CardId = toPlay.Id });

		// Taken one turn BEFORE the doom lands — this is what the player is shown and plays around.
		var preview = DoomPreviewer.Preview(run, state);

		(state, _) = Do(state, new EndTurnAction());
		(state, _) = Do(state, new EndTurnAction());
		Assert.That(state.GetBattle().IsOver, Is.True);

		var actual = run.AfterBattle(state);

		Assert.That(
			actual.Deck.Select(c => c.Name).OrderBy(n => n),
			Is.EqualTo(new[] { "Committed", "Committed" }),
			"sanity: Flood duplicated the committed unit and drowned the other"
		);
		Assert.That(preview.Removed.Select(c => c.Name), Is.EqualTo(new[] { "Hoarded" }));
		Assert.That(preview.Added.Count, Is.EqualTo(1));
		Assert.That(preview.Summary, Does.Contain("-1 LOST").And.Contain("+1 gained"));
	}

	[Test]
	public void ThePreviewTracksTheBoardAsThePlayerChangesIt()
	{
		var run = new Run().WithCards([Unit("A", 1, 1), Unit("B", 1, 1), Unit("C", 1, 1)]);
		(var state, _) = run.StartBattle(DoomScenario.Flood, countdown: 3, [Idler()]);

		var before = DoomPreviewer.Preview(run, state);
		Assert.That(before.Removed.Count, Is.EqualTo(3), "commit nothing and lose everything");

		foreach (var card in state.CardsIn(ZoneType.Hand).Take(2).ToList())
			(state, _) = Do(state, new PlayCardAction { CardId = card.Id });

		var after = DoomPreviewer.Preview(run, state);
		Assert.That(after.Removed.Count, Is.EqualTo(1), "two committed, one still to drown");
		Assert.That(after.Added.Count, Is.EqualTo(2));
	}

	[Test]
	public void NuclearPreviewsAsAChangeNotAnAddOrRemove()
	{
		var run = new Run().WithCards([Unit("Exposed", 3, 3)]);
		(var state, _) = run.StartBattle(DoomScenario.Nuclear, countdown: 2, [Idler()]);

		var card = state.CardsIn(ZoneType.Hand).Single();
		(state, _) = Do(state, new PlayCardAction { CardId = card.Id });

		var preview = DoomPreviewer.Preview(run, state);

		Assert.That(preview.Added, Is.Empty);
		Assert.That(preview.Removed, Is.Empty);
		Assert.That(preview.Changed.Count, Is.EqualTo(1));
		Assert.That(preview.Changed[0].Before.Power, Is.EqualTo(3));
		Assert.That(preview.Changed[0].After.Power, Is.EqualTo(5));
		Assert.That(preview.Summary, Does.Contain("1 changed"));
	}

	[Test]
	public void AnUnimplementedScenarioSaysSoRatherThanShowingAnEmptyDiff()
	{
		var run = new Run().WithCards([Unit("Offering", 1, 1)]);
		(var state, _) = run.StartBattle(DoomScenario.Rapture, countdown: 2, [Idler()]);

		var preview = DoomPreviewer.Preview(run, state);

		Assert.That(preview.IsAvailable, Is.False);
		Assert.That(preview.Summary, Does.Contain("no transform implemented"));
	}

	[Test]
	public void PreviewingDoesNotChangeTheRunOrTheBattle()
	{
		var run = new Run().WithCards([Unit("A", 1, 1)]);
		(var state, _) = run.StartBattle(DoomScenario.Flood, countdown: 3, [Idler()]);

		var runBefore = run;
		var countdownBefore = state.GetBattle().CountdownRemaining;

		DoomPreviewer.Preview(run, state);

		Assert.That(run, Is.EqualTo(runBefore));
		Assert.That(state.GetBattle().CountdownRemaining, Is.EqualTo(countdownBefore));
	}
}
