using System.Collections.Immutable;
using ImmutableGameObjects;

namespace DoomCore.Tests;

/// <summary>
/// The preview must always agree with what actually happens. It is generated by running the real
/// transform, so the decisive test is that preview-then-resolve equals resolve.
/// </summary>
public class DoomPreviewTests
{
	private static (GameState State, ImmutableList<GameEvent> Events) Do(
		GameState state,
		GameAction action
	) => state.AddAction(action).ProcessAllActions();

	private static RunCard Unit(string name, int power, int toughness, int cost = 0) =>
		new()
		{
			Name = name,
			Cost = cost,
			IsUnit = true,
			Power = power,
			Toughness = toughness,
		};

	private static Enemy Idler() =>
		new()
		{
			Name = "Idler",
			Health = 50,
			MaxHealth = 50,
			Intent = IntentKind.Wait,
		};

	/// <summary>
	/// The dial and the apocalypse must agree. Both run the same transform over the same captured
	/// firing, so the only way they can differ is if someone writes a second account of a scenario.
	/// </summary>
	[Test]
	public void ThePreviewMatchesWhatTheDoomActuallyDoes()
	{
		var run = new Run { Life = 100, MaxLife = 100 }.WithCards(
			[Unit("Exposed", 2, 2), Unit("Hoarded", 1, 1)]
		);
		var exposedId = run.Deck[0].RunCardId;

		(var state, _) = run.StartBattle(
			DoomScenario.Nuclear,
			countdown: 2,
			[Idler()],
			opponentHealth: 500
		);

		// Burn the first turn; the doom lands at the end of the SECOND.
		(state, _) = Do(state, new EndTurnAction());

		var toPlay = state.CardsIn(ZoneType.Hand).First(c => c.RunCardId == exposedId);
		(state, _) = Do(state, new PlayCardAction { CardId = toPlay.Id, Lane = 0 });

		// **Taken on the FIRING TURN, and in v3 that is the only turn it is true on.** The preview
		// answers "what would happen if it fired against what is standing right now", and in v3
		// nothing is standing a turn from now — so a preview taken a turn early describes a board
		// that will not exist. See DoomV3Plan.md: the front end must not show this as a forecast on
		// any turn but the last one, or the player is planning around a lie.
		var preview = DoomPreviewer.Preview(run, state);

		(state, _) = Do(state, new EndTurnAction());

		// The doom fired; the battle is still going, because only the Opponent's death ends one.
		Assert.That(state.GetBattle().DoomsFired, Is.EqualTo(1));

		var actual = run.AfterBattle(state);

		Assert.That(
			actual.Deck.Single(c => c.Name == "Exposed").Power,
			Is.EqualTo(2 + DoomTransforms.IrradiatedBuff),
			"sanity: Nuclear irradiated what was standing"
		);
		Assert.That(
			preview.Changed.Select(c => c.Before.Name),
			Is.EqualTo(new[] { "Exposed" }),
			"and the preview said exactly that, a turn earlier"
		);
		Assert.That(
			preview.Changed.Single().After.Power,
			Is.EqualTo(2 + DoomTransforms.IrradiatedBuff)
		);
		Assert.That(preview.Summary, Does.Contain("1 changed"));
	}

	/// <summary>
	/// A BATTLE-scope scenario changes no deck, so a deck diff would report "nothing would change" —
	/// true, and indistinguishable from a broken preview. It reports the board instead and says
	/// plainly that nothing permanent is coming.
	/// </summary>
	[Test]
	public void ABattleScopeDoomPreviewsTheBoardAndSaysNothingIsPermanent()
	{
		var run = new Run { Life = 100, MaxLife = 100 }.WithCards(
			[Unit("A", 1, 1), Unit("B", 1, 1)]
		);

		(var state, _) = run.StartBattle(
			DoomScenario.Flood,
			countdown: 3,
			[Idler()],
			opponentHealth: 500
		);

		var empty = DoomPreviewer.Preview(run, state);
		Assert.That(empty.IsPermanent, Is.False);
		Assert.That(empty.Removed, Is.Empty, "it takes nothing from the deck, ever");
		Assert.That(empty.Summary, Does.Contain("nothing permanent"));

		// The companion is already standing, so the wash has something to take from the start.
		Assert.That(empty.UnitsSwept, Is.Zero, "the companion rides it out");

		foreach (var card in state.CardsIn(ZoneType.Hand).Take(2).ToList())
			(state, _) = Do(
				state,
				new PlayCardAction { CardId = card.Id, Lane = state.OpenLanes().First() }
			);

		var committed = DoomPreviewer.Preview(run, state);

		Assert.That(committed.UnitsSwept, Is.EqualTo(2), "the more you commit, the more it takes");
		Assert.That(committed.Summary, Does.Contain("2 swept"));
	}

	[Test]
	public void NuclearPreviewsAsAChangeNotAnAddOrRemove()
	{
		var run = new Run().WithCards([Unit("Exposed", 3, 3)]);
		(var state, _) = run.StartBattle(DoomScenario.Nuclear, countdown: 2, [Idler()]);

		var card = state.CardsIn(ZoneType.Hand).Single();
		(state, _) = Do(state, new PlayCardAction { CardId = card.Id });

		var preview = DoomPreviewer.Preview(run, state);

		Assert.That(preview.Added, Is.Empty);
		Assert.That(preview.Removed, Is.Empty);
		Assert.That(preview.Changed.Count, Is.EqualTo(1));
		Assert.That(preview.Changed[0].Before.Power, Is.EqualTo(3));
		Assert.That(preview.Changed[0].After.Power, Is.EqualTo(3 + DoomTransforms.IrradiatedBuff));
		Assert.That(preview.Summary, Does.Contain("1 changed"));
	}

	[Test]
	public void AnUnimplementedScenarioSaysSoRatherThanShowingAnEmptyDiff()
	{
		var run = new Run().WithCards([Unit("Offering", 1, 1)]);
		(var state, _) = run.StartBattle(DoomScenario.Rapture, countdown: 2, [Idler()]);

		var preview = DoomPreviewer.Preview(run, state);

		Assert.That(preview.IsAvailable, Is.False);
		Assert.That(preview.Summary, Does.Contain("no transform implemented"));
	}

	[Test]
	public void PreviewingDoesNotChangeTheRunOrTheBattle()
	{
		var run = new Run().WithCards([Unit("A", 1, 1)]);
		(var state, _) = run.StartBattle(DoomScenario.Flood, countdown: 3, [Idler()]);

		var runBefore = run;
		var countdownBefore = state.GetBattle().CountdownRemaining;

		DoomPreviewer.Preview(run, state);

		Assert.That(run, Is.EqualTo(runBefore));
		Assert.That(state.GetBattle().CountdownRemaining, Is.EqualTo(countdownBefore));
	}
}
